create table LINKS (
  "id" NUMBER,
  "permalink" TEXT,
  "go" TEXT,
  "url" TEXT,
  "from" TEXT,
  "sub" TEXT,
  "status" TEXT,
  "user" TEXT,
  "clicks" NUMBER,
  "votes" NUMBER,
  "negatives" NUMBER,
  "karma" NUMBER,
  "comments" NUMBER,
  "title" TEXT,
  "tags" TEXT,
  "sent_date" NUMBER,
  "date" NUMBER,
  "content" TEXT,
  "user_id" NUMBER,
  PRIMARY KEY (id)
);
